# -*- coding: utf-8 -*-
"""G.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cKEAwRqGpdgv_eZxNyUVoB_ITIisXAfD
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split, RandomizedSearchCV
import lightgbm as lab

data_star = pd.read_csv('/content/drive/MyDrive/مسابقة كاجل/train.csv')

data_star.head()

data_star.describe()

data_star.info()

data_star.shape

data_star.isnull().sum()

data_star['class'].sort_values()

data_sample = data_star.sample(n=10000, random_state=42)

from typing import Text
plt.style.use('dark_background')
plt.figure(figsize=(18, 5))

plt.subplot(1, 3, 1)
sns.boxplot(data=data_sample, x='class', y='redshift', hue='class',palette='viridis')
plt.title('How Redshift Separates Classes')
plt.xlabel('Stellar Class')
plt.ylabel('Redshift')

data_sample['u_g'] = data_sample['u'] - data_sample['g']
plt.subplot(1, 3, 2)
sns.scatterplot(data=data_sample, x='u_g', y='redshift', hue='class', alpha=0.6, palette='Set1')
plt.title('Color Index (u-g) vs Redshift')
plt.xlabel('Color Index (u - g)')
plt.ylabel('Redshift')

plt.subplot(1, 3, 3)
sns.countplot(data=data_sample, x='class', hue='class',palette='Accent')
plt.title('Class Distribution (Sample)')
plt.xlabel('Stellar Class')
plt.ylabel('Count')

plt.tight_layout()
plt.show()

print("--- Distribution of Spectral Type across Classes ---")
spectral_table = pd.crosstab(data_star['spectral_type'], data_star['class'], margins=True)
display(spectral_table)

print("\n" + "="*50 + "\n")

print("--- Distribution of Galaxy Population across Classes ---")
population_table = pd.crosstab(data_star['galaxy_population'], data_star['class'], margins=True)
display(population_table)

plt.figure(figsize=(15, 6))


plt.subplot(1, 2, 1)

sns.countplot(data=data_star, x='galaxy_population', hue='class', palette='Set2')
plt.title('Galaxy Population vs Stellar Class')
plt.xticks(rotation=45)
plt.xlabel('Galaxy Population')
plt.ylabel('Count')

plt.subplot(1, 2, 2)
sns.countplot(data=data_star, x='spectral_type', hue='class', palette='Set1')
plt.title('Spectral Type vs Stellar Class')
plt.xticks(rotation=45)
plt.xlabel('Spectral Type')
plt.ylabel('Count')

plt.tight_layout()
plt.show()

data_encoded = data_star.copy()

le_spectral = LabelEncoder()
data_encoded['spectral_type'] = le_spectral.fit_transform(data_encoded['spectral_type'].astype(str))

le_population = LabelEncoder()
data_encoded['galaxy_population'] = le_population.fit_transform(data_encoded['galaxy_population'].astype(str))

le_class = LabelEncoder()
data_encoded['class'] = le_class.fit_transform(data_encoded['class'].astype(str))

data_encoded.head()

print(dict(zip(le_class.classes_, le_class.transform(le_class.classes_))))
print(dict(zip(le_population.classes_, le_population.transform(le_population.classes_))))
print(dict(zip(le_spectral.classes_, le_spectral.transform(le_spectral.classes_))))

data_encoded.corr()['class'].sort_values()

X = data_encoded.drop(columns=['id', 'class'])
y = data_encoded['class']

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)


model = lab.LGBMClassifier(random_state=42, n_estimators=100)
model.fit(X_train, y_train)

y_pred = model.predict(X_val)
accuracy = accuracy_score(y_val, y_pred)
print(f"Accuracy: {accuracy:.5f}")

feature_imp = pd.DataFrame(sorted(zip(model.feature_importances_, X.columns)), columns=['Value','Feature'])

plt.figure(figsize=(10, 6))
sns.barplot(x="Value", y="Feature", data=feature_imp.sort_values(by="Value", ascending=False), hue="Feature", legend=False, palette="plasma")
plt.title('True Relationship: LightGBM Feature Importance for Star Class')
plt.xlabel('Importance Score (Number of Splits)')
plt.ylabel('Features')
plt.tight_layout()
plt.show()

data_encoded['u_g'] = data_encoded['u'] - data_encoded['g']
data_encoded['g_r'] = data_encoded['g'] - data_encoded['r']
data_encoded['r_i'] = data_encoded['r'] - data_encoded['i']
data_encoded['i_z'] = data_encoded['i'] - data_encoded['z']

data_encoded['u_r'] = data_encoded['u'] - data_encoded['r']
data_encoded['g_i'] = data_encoded['g'] - data_encoded['i']

data_encoded['redshift_r'] = data_encoded['redshift'] * data_encoded['r']

X_advanced = data_encoded.drop(columns=['id', 'class'])
y_advanced = data_encoded['class']

X_train_adv, X_val_adv, y_train_adv, y_val_adv = train_test_split(
X_advanced, y_advanced, test_size=0.2, random_state=42, stratify=y_advanced
)

model_adv = lab.LGBMClassifier(random_state=42, n_estimators=1000, learning_rate=0.07)
model_adv.fit(X_train_adv, y_train_adv)

y_pred_adv = model_adv.predict(X_val_adv)
advanced_accuracy = accuracy_score(y_val_adv, y_pred_adv)

print(f"Baseline Accuracy: {accuracy * 100:.5f}%")
print(f" Advanced Feature Engineering Accuracy: {advanced_accuracy * 100:.5f}%")

data_encoded['u_g'] = data_encoded['u'] - data_encoded['g']
data_encoded['g_r'] = data_encoded['g'] - data_encoded['r']
data_encoded['r_i'] = data_encoded['r'] - data_encoded['i']
data_encoded['i_z'] = data_encoded['i'] - data_encoded['z']

data_encoded['u_r'] = data_encoded['u'] - data_encoded['r']
data_encoded['g_i'] = data_encoded['g'] - data_encoded['i']

data_encoded['redshift_r'] = data_encoded['redshift'] * data_encoded['r']

X_advanced = data_encoded.drop(columns=["id", "class"])
y_advanced = data_encoded["class"]


X_train_adv, X_val_adv, y_train_adv, y_val_adv = train_test_split(
X_advanced, y_advanced, test_size=0.2, random_state=42, stratify=y_advanced
)

base_model = lab.LGBMClassifier(random_state=42)

param_distributions = {
"learning_rate": [0.01, 0.03, 0.05, 0.1, 0.2],
"n_estimators": [100, 300, 500, 800, 1000],
"max_depth": [5, 7, 10, -1],
"num_leaves": [20, 31, 50, 70, 127],
"subsample": [0.7, 0.8, 0.9, 1.0],
}


n_iter=10

cv=5

random_search = RandomizedSearchCV(
estimator=base_model,
param_distributions=param_distributions,
n_iter=10,
cv=5,
scoring="accuracy",
random_state=42,
n_jobs=-1,
verbose=1,
)

print(" Starting Randomized Search... Please wait a moment.")

random_search.fit(X_train_adv, y_train_adv)

print("\n" + "=" * 40)
print("Best Hyperparameters Found:", random_search.best_params_)
print(f"Best CV Training Accuracy: {random_search.best_score_ * 100:.5f}%")
print("=" * 40 + "\n")


best_model = random_search.best_estimator_
y_val_pred = best_model.predict(X_val_adv)
final_val_accuracy = accuracy_score(y_val_adv, y_val_pred)

print(
f"Final Validation Accuracy with Best Model: {final_val_accuracy * 100:.5f}%"
)